### PR TITLE
Add Jolokia

### PR DESCRIPTION
**Pull request by ngvlongit1**
Add Jilokia HTTP Server to monitoring metric of kafka

### CODE REVIEW

**Comment by sscaling** [comment]
Thanks for the PR, however - I don't think we're interested in adding jolokia to the project at this time as it is outside the core Apache Kafka offerings (which is what this image packages). It also seems a fairly inactive project judging by the github repo: https://github.com/rhuss/jolokia

I'll leave the PR open for a bit to allow for further comment, but I suspect it's easier just to mount the JAR and configure `KAFKA_OPTS` or make a new image with `wurstmeister/kafka` as the base with your specific extras included.

**Comment by ngvlong** [comment]
Thanks for the review.
I think Jolokia is useful for monitoring. Mount JAR to images and set execute for file is  not secure.
Do you know why my PR is failed on Travis? I did not edit any case of test.

**Comment by sscaling** [comment]
> I think Jolokia is useful for monitoring

This is subjective and adds an additional component to maintain. It is not critical to running Kafka which is why I don't think it's universally required.

> Do you know why my PR is failed on Travis?

Looks related to #451 - I have raised #452 as a work-around

**Comment by ngvlong** [comment]
> > Do you know why my PR is failed on Travis?
> 
> Looks related to #451 - I have raised #452 as a work-around

Thanks

**Comment by alvarolmedo** [comment]
+1

**Comment by alvarolmedo** [comment]
Jolokia is active, exists commits in the last month.
I've created the PR #503 to integrate with jolokia's version 1.6.1 based in this PR of @ngvlongit1.

**Comment by sscaling** [comment]
Thanks @alvarolmedo - but my comments still stand. This is not a universal solution - and not something that we want to maintain at this point in time.

**Comment by ebuildy** [comment]
Jolikia is very famous project to monitor JVM application. About Kafka, we use elastic-beat https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-kafka.html.

As Docker build principle, all Jolikia related stuff should come at the end of the Dockerfile.

What about to create a tag suffit such as "with-jolikia" ?

**Comment by ebuildy** [comment]
Or maybe, a simple wiki post, or a Dockerfile example such as :

```
FROM wurstmeister/kafka:1.0.0

ENV KAFKA_JOLOKIA_PORT=7777

RUN TRG="$KAFKA_HOME/libs/jolokia-jvm-1.6.0-agent.jar" && \
    wget "http://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-jvm/1.6.0/jolokia-jvm-1.6.0-agent.jar" -O ${TRG} && \
    chmod a+x ${TRG}

ENV KAFKA_OPTS="-javaagent:$KAFKA_HOME/libs/jolokia-jvm-1.6.0-agent.jar=port=$KAFKA_JOLOKIA_PORT,host=0.0.0.0 $KAFKA_OPTS"
```

**Pull request closed without merging**
