### PR TITLE
Fix compatibility with docker-compose 1.23.1

### LINKED ISSUE #537: Travis build broken with docker-compose 1.23
Travis is currently running docker-compose 1.23.1 which mangles the container names (appends a random sha to each one). This breaks various parts of the test process, blocking any further changes. 

This change was reverted in 1.23.2 (https://github.com/docker/compose/releases/tag/1.23.2). In the mean time we can be a bit more explicit in the tests to hopefully prevent this kind of breakage in the future.

### PR DESCRIPTION
**Pull request by sscaling**
Fixes #537

### CODE REVIEW

**Comment by wurstmeister** [comment]
check for an alternative https://github.com/wurstmeister/kafka-docker/pull/538

**Comment by sscaling** [comment]
I considered this, but then they seem fragile to future changes as well. This just makes everything explicit and reduces one step in the test. I can go either way on it if you have a strong preference.

**Comment by wurstmeister** [comment]
i definitely think the compose version should be pinned to avoid issues with future breaking changes in compose. 
This change seems to make the compose file a little more verbose just to work around the change that has been reverted again.

**Comment by sscaling** [comment]
Decided that we'll do this and #538

**Pull request merged**
