### PR TITLE
Fix deprecated advertised host name

### PR DESCRIPTION
**Pull request by trajakovic**
Update readme and docker-compose* files.

This addresses #233, and probably fixes latest #211 errors.

### CODE REVIEW

**Comment by trajakovic** [comment]
although this fixes startup issue, kafka brokers don't work outside docker containers

**Comment by trajakovic** [comment]
closing this as it's not complete solution

**Comment by AndrewOrr** [comment]
I think it is a problem with the advertised hostname? When you use the boot2docker ip I can connect outside of the docker container.

**Comment by tcjennings** [comment]
The reason this doesn't work is changing "KAFKA_ADVERTISED_HOST_NAME" TO "KAFKA_ADVERTISED_LISTENERS" is the same as just removing "KAFKA_ADVERTISED_HOST_NAME" entirely.

The resulting broker configures a single listener on port 9092 that will work within Docker but not from outside. To create a broker that will from outside Docker, a more robust listener configuration has to be configured. Specifically, you need 2 listeners, one for inside and one for outside, on different ports, and publish only the outside listener to your host.

**Comment by tcjennings** [comment]
See PR #256

**Pull request closed without merging**
